sudo: required

services:
  - docker

before_install:
  - docker build -t lissenburg/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lissenburg/multi-docker-client-test npm test

after_success:
  # build images
  - docker build -t lissenburg/multi-docker-client ./client
  - docker build -t lissenburg/multi-docker-nginx ./nginx
  - docker build -t lissenburg/multi-docker-server ./server
  - docker build -t lissenburg/multi-docker-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push lissenburg/multi-docker-client
  - docker push lissenburg/multi-docker-nginx
  - docker push lissenburg/multi-docker-server
  - docker push lissenburg/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-505452423620'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
