version: '3.7'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - api
      - client

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD

  redis:
    image: redis:latest

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
